packages:
  - "apps/**"
  - "!apps/backend/.medusa/**"
allowBuilds:
  '@medusajs/telemetry': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

overrides:
  "@types/react": "19.0.5"
  "@types/react-dom": "19.0.5"
