import { ThemeProvider } from "@/components/shared/theme-provider";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import { fontVariables } from "@/lib/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "EzCommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased")}
      suppressHydrationWarning
    >
      <body className={cn("min-h-full flex flex-col", fontVariables)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          // enableSystem
          disableTransitionOnChange
        >
          <NuqsAdapter>{children}</NuqsAdapter>
        </ThemeProvider>
      </body>
    </html>
  );
}
