import { cn } from "@/lib/utils";
import type { Metadata } from "next";

import { RootWrapper } from "@/components/shared/root-wrapper";
import { fontVariables } from "@/lib/font";
import "./globals.css";


export const metadata: Metadata = {
  title: "EzCommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased")}
      suppressHydrationWarning
    >
      <body className={cn("min-h-full flex flex-col", fontVariables)}>
        <RootWrapper>{children}</RootWrapper>
      </body>
    </html>
  );
}
