services:
  postgres:
    image: postgres:17
    container_name: medusa-postgres

    restart: unless-stopped

    ports:
      - "5433:5432"

    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: medusa
      POSTGRES_DB: medusa

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
